name = "DapplegrayTest"
uuid = "bab38649-35e3-4f6a-a158-95a28af37545"
authors = ["Rory Hubbard <calvin3h@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DapplegrayDynamics = "66339b55-5b40-4d14-8f64-063c89b7ed2d"

[compat]
julia = "1.11.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
